x-development-volumes: &development-volumes
  volumes:
    - ./docs:/workspace/app/docs/
    - ./tests:/workspace/app/tests/
    - ./src:/workspace/app/src/
    - ./Makefile:/workspace/app/Makefile
    - ./pyproject.toml:/workspace/app/pyproject.toml
    - ./poetry.lock:/workspace/app/poetry.lock
    - ./.env.docker.example:/workspace/app/.env

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    ports:
      - "8000:8000"
    tty: true
    command: poetry run app run --reload --host 0.0.0.0 --port 8000
    restart: always
    <<: *development-volumes
  migrator:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    command: litestar database upgrade --no-prompt
    restart: "no"
    <<: *development-volumes
    env_file:
      - .env.docker.example
    depends_on:
      db:
        condition: service_healthy
