name: app-production

services:
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    hostname: db
    environment:
      POSTGRES_PASSWORD: "app"
      POSTGRES_USER: "app"
      POSTGRES_DB: "app"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - app
      interval: 2s
      timeout: 3s
      retries: 40
  app:
    build:
      context: .
      dockerfile: deploy/docker/run/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env.docker.example
  migrator:
    build:
      context: .
      dockerfile: deploy/docker/run/Dockerfile
    restart: "no"
    command: litestar database upgrade --no-prompt
    env_file:
      - .env.docker.example
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data: {}
